#
#
# Constants file for point information reader



#
# Useful constants
# ----------------

#
# All panels can support up-to-8 loops.
# Profile slot card panels can support up-to 32
MAX_LOOP_TO_SCAN = 8

# This is fixed, (250) here to make code easier to read.
MAX_ADDRESSES_PER_LOOP = 250

PACKET_ID_POINT_INFO_REQUEST = 148
PACKET_ID_POINT_INFO_REPLY   = 149
PACKET_ID_PANEL_INFORMATION  = 27


# Standard offset within packet header
OFFSET_FOR_PACKET_TYPE_MXSPEAK_6 = 9 

OFFSET_FOR_PACKET_TYPE_MXSPEAK_5 = 8

# offsets within Point Information Reply Packet
POINT_REPLY_HIGH_LEVEL_STATUS_OFFSET = 10   
POINT_REPLY_FLAGS_OFFSET             = 11
POINT_REPLY_NODE_OFFSET              = 12
POINT_REPLY_CHANNEL_OFFSET           = 13
POINT_REPLY_CHANNEL_ADDRR_OFFSET     = 14
POINT_REPLY_POINT_CATEGORY_OFFSET    = 15
POINT_REPLY_POINT_ADDRESS_OFFSET     = 16

POINT_REPLY_LOG_ADDR_PART_1_OFFSET   = 17
POINT_REPLY_LOG_ADDR_PART_2_OFFSET   = 18
POINT_REPLY_DEVICE_TYPE_OFFSET       = 19
POINT_REPLY_ATTRIBS_OFFSET           = 20
POINT_REPLY_GROUP_PT1_OFFSET         = 21
POINT_REPLY_GROUP_PT2_OFFSET         = 22
POINT_REPLY_AREA_TYPE_OFFSET         = 23


# offsets within point information request packet
POINT_INFO_REQUEST_NODE_OFFSET       = 10   
POINT_INFO_REQUEST_CHANNEL_OFFSET    = 11
POINT_INFO_REQUEST_LOOP_OFFSET       = 12
POINT_INFO_REQUEST_POINT_CATEGORY_OFFSET = 13
POINT_INFO_REQUEST_POINT_OFFSET      = 14   
POINT_INFO_REQUEST_LOGICAL_ADDR_PT1_OFFSET = 15
POINT_INFO_REQUEST_LOGICAL_ADDR_PT2_OFFSET = 16
POINT_INFO_REQUEST_DEVICE_CATEGORY_OFFSET  = 17



# FAKE VALUES
DEVICE_ID_855_PH  = 123
DEVICE_ID_855_P   = 124
# Real values
DEVICE_ID_855_H   = 135
DEVICE_ID_855_PC  = 136