#
#
# Constants file for point information reader



#
# Useful constants
# ----------------

#
# All panels can support up-to-8 loops.
# Profile slot card panels can support up-to 32
MAX_LOOP_TO_SCAN = 8

# This is fixed, (250) here to make code easier to read.
MAX_ADDRESSES_PER_LOOP = 250

PACKET_ID_POINT_INFO_REQUEST = 148
PACKET_ID_POINT_INFO_REPLY   = 149
PACKET_ID_PANEL_INFORMATION  = 27
PACKET_ID_PANEL_INFORMATION_REQ  = 26
PACKET_ID_CHECKER_REGISTER           = 209
PACKET_ID_CHECKER_REGISTRATION_REPLY = 210


# Standard offset within packet header
OFFSET_FOR_PACKET_TYPE_MXSPEAK_6 = 9 

OFFSET_FOR_PACKET_TYPE_MXSPEAK_5 = 8

# offsets within Point Information Reply Packet
POINT_REPLY_HIGH_LEVEL_STATUS_OFFSET = 10   
POINT_REPLY_FLAGS_OFFSET             = 11
POINT_REPLY_NODE_OFFSET              = 12
POINT_REPLY_CHANNEL_OFFSET           = 13
POINT_REPLY_CHANNEL_ADDRR_OFFSET     = 14
POINT_REPLY_POINT_CATEGORY_OFFSET    = 15
POINT_REPLY_POINT_ADDRESS_OFFSET     = 16

POINT_REPLY_LOG_ADDR_PART_1_OFFSET   = 17
POINT_REPLY_LOG_ADDR_PART_2_OFFSET   = 18
POINT_REPLY_DEVICE_TYPE_OFFSET       = 19
POINT_REPLY_ATTRIBS_OFFSET           = 20
POINT_REPLY_GROUP_PT1_OFFSET         = 21
POINT_REPLY_GROUP_PT2_OFFSET         = 22
POINT_REPLY_AREA_TYPE_OFFSET         = 23

POINT_REPLY_AREA_NUMNER              = 24 
POINT_REPLY_SECTOR                   = 25 
POINT_REPLY_LOOP_TYPE                = 26
POINT_REPLY_RAW_DEV_ID               = 27 
POINT_REPLY_ACTUAL_DEVICE_TYPE       = 28
POINT_REPLY_MODE_AND_SENS            = 29
#
POINT_REPLY_RAW_ANALOGUE_1      = 30
POINT_REPLY_RAW_ANALOGUE_2      = 31
POINT_REPLY_RAW_ANALOGUE_3      = 32
#
POINT_REPLY_LTA_FLAGS           = 33
POINT_REPLY_RAW_LTA             = 34
POINT_REPLY_DIRTINESS           = 35
#
POINT_REPLY_UNIT_OF_MEASURE_1   = 36
POINT_REPLY_UNIT_OF_MEASURE_2   = 37
POINT_REPLY_UNIT_OF_MEASURE_3   = 38
#
POINT_REPLY_CONVERTED_VALUE_1   = 39
POINT_REPLY_CONVERTED_VALUE_2   = 40
POINT_REPLY_CONVERTED_VALUE_3   = 41
#
POINT_REPLY_INSTANT_ACTIVE      = 42
POINT_REPLY_INSTANT_FAULT       = 43
POINT_REPLY_CONFIRMED_ACTIVE    = 44
POINT_REPLY_CONFIRMED_FAULT     = 45
POINT_REPLY_ACKED_ACTIVE        = 46
POINT_REPLY_ACKED_FAULT         = 47
#
POINT_REPLY_IS_OUTPUT_FORCED    = 48
POINT_REPLY_OUTPUT_UNFORCED_STATE  = 49
POINT_REPLY_OUTPUT_FORCED_STATE = 50



# offsets within point information request packet
POINT_INFO_REQUEST_NODE_OFFSET       = 10   
POINT_INFO_REQUEST_CHANNEL_OFFSET    = 11
POINT_INFO_REQUEST_LOOP_OFFSET       = 12
POINT_INFO_REQUEST_POINT_CATEGORY_OFFSET = 13
POINT_INFO_REQUEST_POINT_OFFSET      = 14   
POINT_INFO_REQUEST_LOGICAL_ADDR_PT1_OFFSET = 15
POINT_INFO_REQUEST_LOGICAL_ADDR_PT2_OFFSET = 16
POINT_INFO_REQUEST_DEVICE_CATEGORY_OFFSET  = 17


# The unit of measure value in the
# point information reply packet
CHANNEL_TYPE_INVALID       = 0
CHANNEL_TYPE_DEGREES_C     = 1
CHANNEL_TYPE_DEGREES_F     = 2
CHANNEL_TYPE_PPM           = 3
CHANNEL_TYPE_PERCENT_FOOT  = 4
CHANNEL_TYPE_PERCENT_METER = 5
CHANNEL_TYPE_Y_VALUE       = 6
CHANNEL_TYPE_AMPS          = 7
CHANNEL_TYPE_VOLTS         = 8
CHANNEL_TYPE_NOT_INSTALLED = 9
CHANNEL_TYPE_MILLI_AMP     = 10

# decoding the instantaneous alarm state
# in the point info reply packet
POINT_REPLY_INSTANT_ALARM_STATE_CLEAR      = 0 
POINT_REPLY_INSTANT_ALARM_STATE_PRE_ALARM  = 1 
POINT_REPLY_INSTANT_ALARM_STATE_VERIFYING  = 2 
POINT_REPLY_INSTANT_ALARM_STATE_ACTIVE     = 3
POINT_REPLY_INSTANT_ALARM_STATE_RESETTING  = 4
POINT_REPLY_INSTANT_ALARM_STATE_TEST       = 5 
POINT_REPLY_INSTANT_ALARM_STATE_WARNING    = 6





# FAKE VALUES
DEVICE_ID_855_PH  = 123
DEVICE_ID_855_P   = 124
# Real values
DEVICE_ID_855_H   = 135
DEVICE_ID_855_PC  = 136